# Generated by Django 5.0.3 on 2024-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_signals', '0002_threadtrackingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalBehave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
